inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rails-accessibility

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - rails_app/db/schema.rb

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpecRails/InferredSpecType:
  Enabled: false

FactoryBot/AssociationStyle:
  EnforcedStyle: explicit

# One more than the smallest paginated page size.
FactoryBot/ExcessiveCreateList:
  MaxAmount: 11

# Prefer greater nesting depth for better organization.
RSpec/NestedGroups:
  Max: 6
