require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/components", type: :request do
  subject!(:component) { create(:component) }

  fixtures :components

  let(:valid_attributes) {
    {
      name: "Test Component",
      description: "A component for testing purposes",
      lifecycle: "experimental",
      type: "api",
      image_url: "https://example.com/image.png",
      repository_url: "https://example.com/example/component.git"
    }
  }

  let(:invalid_attributes) {
    {
      lifecycle: "invalid_lifecycle",
      type: "invalid_type",
      image_url: "gopher://example.com/image.png",
      repository_url: "ftp://example.com/example/component.git"
    }
  }

  context "when the user is not authenticated" do
    describe "GET /components" do
      it_behaves_like 'an action that requires authentication', :get, -> { components_path }
    end

    describe "GET /components/:id" do
      it_behaves_like 'an action that requires authentication', :get, -> { component_path(component) }
    end

    describe "GET /components/new" do
      it_behaves_like 'an action that requires authentication', :get, -> { new_component_path }
    end

    describe "GET /components/:id/edit" do
      it_behaves_like 'an action that requires authentication', :get, -> { edit_component_path(component) }
    end

    describe "POST /components" do
      it_behaves_like 'an action that requires authentication', :post, -> { components_path }
    end

    describe "PATCH /components/:id" do
      it_behaves_like 'an action that requires authentication', :patch, -> { component_path(component) }
    end

    describe "DELETE /components/:id" do
      it_behaves_like 'an action that requires authentication', :delete, -> { component_path(component) }
    end
  end

  context "when the user is authenticated" do
    requires_authentication

    describe "GET /components" do
      it "renders a successful response" do
        get components_url
        expect(response).to be_successful
      end
    end

    describe "GET /components/:id" do
      it "renders a successful response" do
        get component_url(component)
        expect(response).to be_successful
      end
    end

    describe "GET /components/new" do
      it "renders a successful response" do
        get new_component_url
        expect(response).to be_successful
      end
    end

    describe "GET /components/:id/edit" do
      it "renders a successful response" do
        get edit_component_url(component)
        expect(response).to be_successful
      end
    end

    describe "POST /components" do
      context "with valid parameters" do
        it "creates a new component" do
          expect {
            post components_url, params: { component: valid_attributes }
          }.to change(Component, :count).by(1)
        end

        it "redirects to the created component" do
          post components_url, params: { component: valid_attributes }
          expect(response).to redirect_to(component_url(Component.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new component" do
          expect {
            post components_url, params: { component: invalid_attributes }
          }.not_to change(Component, :count)
        end

        it "renders a response with 422 status" do
          post components_url, params: { component: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_content)
        end
      end
    end

    describe "PATCH /components/:id" do
      context "with valid parameters" do
        let(:new_attributes) {
          {
            lifecycle: "production"
          }
        }

        it "updates the requested component" do
          patch component_url(component), params: { component: new_attributes }
          component.reload
          expect(component.lifecycle).to eq("production")
        end

        it "redirects to the component" do
          patch component_url(component), params: { component: new_attributes }
          component.reload
          expect(response).to redirect_to(component_url(component))
        end
      end

      context "with invalid parameters" do
        it "renders a response with 422 status" do
          patch component_url(component), params: { component: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_content)
        end
      end
    end

    describe "DELETE /components/:id" do
      it "destroys the requested component" do
        expect {
          delete component_url(component)
        }.to change(Component, :count).by(-1)
      end

      it "redirects to the components list" do
        delete component_url(component)
        expect(response).to redirect_to(components_url)
      end
    end
  end
end
