# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/deployments", type: :request do
  fixtures :components

  requires_authentication

  let(:valid_attributes) {
    {
      environment: "production",
      platform: "aws",
      component_id: components(:one).id
    }
  }

  let(:invalid_attributes) {
    {
      environment: "invalid_environment",
      platform: "invalid_platform",
      component_id: nil
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Deployment.create! valid_attributes
      get deployments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      deployment = Deployment.create! valid_attributes
      get deployment_url(deployment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_deployment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      deployment = Deployment.create! valid_attributes
      get edit_deployment_url(deployment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Deployment" do
        expect {
          post deployments_url, params: { deployment: valid_attributes }
        }.to change(Deployment, :count).by(1)
      end

      it "redirects to the created deployment" do
        post deployments_url, params: { deployment: valid_attributes }
        expect(response).to redirect_to(deployment_url(Deployment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Deployment" do
        expect {
          post deployments_url, params: { deployment: invalid_attributes }
        }.not_to change(Deployment, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post deployments_url, params: { deployment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          platform: "aptible"
        }
      }

      it "updates the requested deployment" do
        deployment = Deployment.create! valid_attributes
        patch deployment_url(deployment), params: { deployment: new_attributes }
        deployment.reload
        expect(deployment.platform).to eq("aptible")
      end

      it "redirects to the deployment" do
        deployment = Deployment.create! valid_attributes
        patch deployment_url(deployment), params: { deployment: new_attributes }
        deployment.reload
        expect(response).to redirect_to(deployment_url(deployment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        deployment = Deployment.create! valid_attributes
        patch deployment_url(deployment), params: { deployment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested deployment" do
      deployment = Deployment.create! valid_attributes
      expect {
        delete deployment_url(deployment)
      }.to change(Deployment, :count).by(-1)
    end

    it "redirects to the deployments list" do
      deployment = Deployment.create! valid_attributes
      delete deployment_url(deployment)
      expect(response).to redirect_to(deployments_url)
    end
  end
end
