require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/systems", type: :request do
  fixtures :domains

  requires_authentication

  let(:valid_attributes) {
    {
      description: "A description for the test system",
      domain_id: domains(:one).id,
      name: "Test System",
      image_url: "https://example.com/image.png",
      status: "active"
    }
  }

  let(:invalid_attributes) {
    {
      domain_id: nil,
      image_url: "invalid_url",
      status: "invalid_status"
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Junction::System.create! valid_attributes
      get systems_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system = Junction::System.create! valid_attributes
      get system_url(system)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      system = Junction::System.create! valid_attributes
      get edit_system_url(system)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new System" do
        expect {
          post systems_url, params: { system: valid_attributes }
        }.to change(System, :count).by(1)
      end

      it "redirects to the created system" do
        post systems_url, params: { system: valid_attributes }
        expect(response).to redirect_to(system_url(System.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new System" do
        expect {
          post systems_url, params: { system: invalid_attributes }
        }.not_to change(System, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post systems_url, params: { system: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          status: "closed"
        }
      }

      it "updates the requested system" do
        system = Junction::System.create! valid_attributes
        patch system_url(system), params: { system: new_attributes }
        system.reload
        expect(system.status).to eq("closed")
      end

      it "redirects to the system" do
        system = Junction::System.create! valid_attributes
        patch system_url(system), params: { system: new_attributes }
        system.reload
        expect(response).to redirect_to(system_url(system))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        system = Junction::System.create! valid_attributes
        patch system_url(system), params: { system: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system" do
      system = Junction::System.create! valid_attributes
      expect {
        delete system_url(system)
      }.to change(System, :count).by(-1)
    end

    it "redirects to the systems list" do
      system = Junction::System.create! valid_attributes
      delete system_url(system)
      expect(response).to redirect_to(systems_url)
    end
  end
end
