require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/domains", type: :request do
  subject!(:domain) { create(:domain) }

  let(:valid_attributes) {
    {
      description: "A domain for testing purposes",
      name: "Test Domain",
      image_url: "https://example.com/image.png",
      status: "active"
    }
  }

  let(:invalid_attributes) {
    {
      image_url: "invalid_url",
      status: "invalid_status"
    }
  }

  context "when the user is not authenticated" do
    describe "GET /index" do
      it_behaves_like "an action that requires authentication", :get, -> { domains_path }
    end

    describe "GET /show" do
      it_behaves_like "an action that requires authentication", :get, -> { domain_path(domain) }
    end

    describe "GET /new" do
      it_behaves_like "an action that requires authentication", :get, -> { new_domain_path }
    end

    describe "GET /edit" do
      it_behaves_like "an action that requires authentication", :get, -> { edit_domain_path(domain) }
    end

    describe "POST /create" do
      it_behaves_like "an action that requires authentication", :post, -> { domains_path }
    end

    describe "PATCH /update" do
      it_behaves_like "an action that requires authentication", :patch, -> { domain_path(domain) }
    end

    describe "DELETE /destroy" do
      it_behaves_like "an action that requires authentication", :delete, -> { domain_path(domain) }
    end
  end

  context "when the user is authenticated" do
    requires_authentication

    describe "GET /index" do
      it_behaves_like "an action that requires permission",
        :get, -> { domains_path }, %w[junction.codes/domains.all.read]

      it "renders a successful response" do
        get domains_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      it_behaves_like "an action that requires permission",
        :get, -> { domain_path(domain) }, %w[junction.codes/domains.all.read]

      it "renders a successful response" do
        get domain_url(domain)
        expect(response).to be_successful
      end
    end

    describe "GET /new" do
      it_behaves_like "an action that requires permission",
        :get, -> { new_domain_path }, %w[junction.codes/domains.all.write]

      it "renders a successful response" do
        get new_domain_url
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      it_behaves_like "an action that requires permission",
        :get, -> { edit_domain_path(domain) }, %w[junction.codes/domains.all.write]

      it "renders a successful response" do
        get edit_domain_url(domain)
        expect(response).to be_successful
      end
    end

    describe "POST /create" do
      it_behaves_like "an action that requires permission",
        :post, -> { domains_path },
        %w[junction.codes/domains.all.write junction.codes/domains.owned.write],
        -> { { domain: valid_attributes.merge(owner_id: current_user.groups.first&.id) } }

      context "with valid parameters" do
        it "creates a new Domain" do
          expect {
            post domains_url, params: { domain: valid_attributes }
          }.to change(Junction::Domain, :count).by(1)
        end

        it "redirects to the created domain" do
          post domains_url, params: { domain: valid_attributes }
          expect(response).to redirect_to(domain_url(Junction::Domain.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new Domain" do
          expect {
            post domains_url, params: { domain: invalid_attributes }
          }.not_to change(Junction::Domain, :count)
        end

        it "renders a response with 422 status (i.e. to display the 'new' template)" do
          post domains_url, params: { domain: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_content)
        end
      end
    end

    describe "PATCH /update" do
      it_behaves_like "an action that requires permission",
        :patch, -> { domain_path(domain) },
        %w[junction.codes/domains.all.write junction.codes/domains.owned.write],
        { domain: { status: "closed" } }

      context "with valid parameters" do
        let(:new_attributes) {
          {
            status: "closed"
          }
        }

        it "updates the requested domain" do
          patch domain_url(domain), params: { domain: new_attributes }
          domain.reload
          expect(domain.status).to eq("closed")
        end

        it "redirects to the domain" do
          patch domain_url(domain), params: { domain: new_attributes }
          domain.reload
          expect(response).to redirect_to(domain_url(domain))
        end
      end

      context "with invalid parameters" do
        it "renders a response with 422 status (i.e. to display the 'edit' template)" do
          patch domain_url(domain), params: { domain: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_content)
        end
      end
    end

    describe "DELETE /destroy" do
      it_behaves_like "an action that requires permission",
        :delete, -> { domain_path(domain) },
        %w[junction.codes/domains.all.destroy junction.codes/domains.owned.destroy]

      it "destroys the requested domain" do
        expect {
          delete domain_url(domain)
        }.to change(Junction::Domain, :count).by(-1)
      end

      it "redirects to the domains list" do
        delete domain_url(domain)
        expect(response).to redirect_to(domains_url)
      end
    end
  end
end
