require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/groups", type: :request do
  subject!(:group) { create(:group) }

  let(:valid_attributes) {
    {
      name: "Test Group",
      description: "A group for testing purposes",
      type: "team",
      email: "team@example.com"
    }
  }

  let(:invalid_attributes) {
    {
      email: "invalid-email"
    }
  }

  context "when the user is not authenticated" do
    describe "GET /index" do
      it_behaves_like "an action that requires authentication", :get, -> { groups_path }
    end

    describe "GET /show" do
      it_behaves_like "an action that requires authentication", :get, -> { group_path(group) }
    end

    describe "GET /new" do
      it_behaves_like "an action that requires authentication", :get, -> { new_group_path }
    end

    describe "GET /edit" do
      it_behaves_like "an action that requires authentication", :get, -> { edit_group_path(group) }
    end

    describe "POST /create" do
      it_behaves_like "an action that requires authentication", :post, -> { groups_path }
    end

    describe "PATCH /update" do
      it_behaves_like "an action that requires authentication", :patch, -> { group_path(group) }
    end

    describe "DELETE /destroy" do
      it_behaves_like "an action that requires authentication", :delete, -> { group_path(group) }
    end
  end

  context "when the user is authenticated" do
    requires_authentication

    describe "GET /index" do
      it_behaves_like "an action that requires permission",
        :get, -> { groups_path }, %w[junction.codes/groups.all.read]

      it "renders a successful response" do
        get groups_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      it_behaves_like "an action that requires permission",
        :get, -> { group_path(group) }, %w[junction.codes/groups.all.read]

      it "renders a successful response" do
        get group_url(group)
        expect(response).to be_successful
      end
    end

    describe "GET /new" do
      it_behaves_like "an action that requires permission",
        :get, -> { new_group_path }, %w[junction.codes/groups.all.write]

      it "renders a successful response" do
        get new_group_url
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      it_behaves_like "an action that requires permission",
        :get, -> { edit_group_path(group) }, %w[junction.codes/groups.all.write]

      it "renders a successful response" do
        get edit_group_url(group)
        expect(response).to be_successful
      end
    end

    describe "POST /create" do
      it_behaves_like "an action that requires permission",
        :post, -> { groups_path },
        %w[junction.codes/groups.all.write junction.codes/groups.owned.write],
        -> { { group: valid_attributes } }

      context "with valid parameters" do
        it "creates a new Group" do
          expect {
            post groups_url, params: { group: valid_attributes }
          }.to change(Junction::Group, :count).by(1)
        end

        it "redirects to the created group" do
          post groups_url, params: { group: valid_attributes }
          expect(response).to redirect_to(group_url(Junction::Group.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new Group" do
          expect {
            post groups_url, params: { group: invalid_attributes }
          }.not_to change(Junction::Group, :count)
        end

        it "renders a response with 422 status (i.e. to display the 'new' template)" do
          post groups_url, params: { group: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_content)
        end
      end
    end

    describe "PATCH /update" do
      it_behaves_like "an action that requires permission",
        :patch, -> { group_path(group) },
        %w[junction.codes/groups.all.write junction.codes/groups.owned.write],
        { group: { type: "business_unit" } }

      context "with valid parameters" do
        let(:new_attributes) {
          {
            type: "business_unit"
          }
        }

        it "updates the requested group" do
          patch group_url(group), params: { group: new_attributes }
          group.reload
          expect(group.type).to eq("business_unit")
        end

        it "redirects to the group" do
          patch group_url(group), params: { group: new_attributes }
          group.reload
          expect(response).to redirect_to(group_url(group))
        end
      end

      context "with invalid parameters" do
        it "renders a response with 422 status (i.e. to display the 'edit' template)" do
          patch group_url(group), params: { group: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_content)
        end
      end
    end

    describe "DELETE /destroy" do
      it_behaves_like "an action that requires permission",
        :delete, -> { group_path(group) },
        %w[junction.codes/groups.all.destroy junction.codes/groups.owned.destroy]

      it "destroys the requested group" do
        expect {
          delete group_url(group)
        }.to change(Junction::Group, :count).by(-1)
      end

      it "redirects to the groups list" do
        delete group_url(group)
        expect(response).to redirect_to(groups_url)
      end
    end
  end
end
